### ISSUE TITLE
5.5.0 버전 사전 리로드 API 질문입니다

### ISSUE THREAD

**Issue by sayco5842** [HowookJeong/elasticsearch-analysis-arirang#4]
안녕하세요

mecab-ko 에서 아리랑 형태소분석기로 변경 예정으로 작업중에 있습니다.

올려주신 5.5.0 버전으로 빌드해서 테스트 중에 있습니다만

사전 변경 후에 _arirang_dictionary_reload 호출 시 에러가 떨어져 질문 올립니다.

illegal_argument_exception "No end point or operation is available at [_arirang_dictionary_reload]

호출 url : curl -XGET http://localhost:9200/_arirang_dictionary_reload

Es 재기동 시에는 변경된 사전이 반영이 잘됩니다.

5.5.0 플러그인에 경우 _arirang_dictionary_reload 따로 구현 해야 되는건지 궁금합니다

**Comment by HowookJeong** [comment]
6.0 에는 테스트를 하고 올렸는데 5.5 버전에는 제가 급하게 올리느라 확인을 못해 봤습니다.
한번 확인해 보도록 하겠습니다.

**Comment by HowookJeong** [comment]
제가 확인을 해보니 정상 동작 하는데요.
혹시 안되시면 에러 로그나 제가 확인 가능한 내용 공유해 주시면 살펴 보도록 하겠습니다.

**Comment by HowookJeong** [comment]
참고로 아래 에러는
illegal_argument_exception "No end point or operation is available at [_arirang_dictionary_reload]
정상적으로 plugin 등록이 되지 않아 RESTful endpoint 를 찾지 못해서 발생 하는 에러 입니다.
아마도 설치 후 클러스터 재시작 하시고 테스트 하시면 잘 되지 않을까 싶습니다.

**Comment by sayco5842** [comment]
확인해주셔서 감사합니다.

플러그인 재설치 및 Es재기동은 여러차례 시도하였습니다만 같은 에러 메세지가 리턴됩니다.ㅠㅠ

elasticsearcg-5.5.0/plugins/analysis-arirang/arirang-morph-1.1.0.jar 파일 안에 dic 파일 직접 수정하고

Es 재기동 시 형태소분석이 정상적으로 이뤄지는 걸로 봐선 플러그인 자체는 설치가 된것으로 보입니다.

확인중에 여쭤보고 싶은 부분이 arirang-analyzer-6 빌드 후 플러그인 설치하는 걸로 알고있는데

설치 순서 
1) arirang-analyzer-6 빌드
  /var/www/setup/arirang-analyzer-6
  mvn install

2) analysis-arirang 플러그인 설치
/var/www/elasticsearch-5.5.0
./bin/elasticsearch-plugin install file:///플러그인 경로

제대로 설치하고 있는지 확인해 주시면 감사하겠습니다.

또 확인중에 

/var/www/setup/arirang-analyzer-6/lib/arirang-morph-1.1.0.jar  dic파일 수정시 Es반영되지 않고

elasticsearcg-5.5.0/plugins/analysis-arirang/arirang-morph-1.1.0.jar dic 파일 수정시 Es반영 됩니다.

정상적인 부분인지 여쭤봅니다. 감사합니다.

**Comment by HowookJeong** [comment]
원인을 찾았습니다.
5.2 랑 5.5 랑 또 소스 코드가 바뀌었내요. ㅡ.ㅡ;
RestAction 등록 하는 부분이 바뀌어서 수정 후 공유 드리겠습니다.

**Comment by HowookJeong** [comment]
수정해서 commit 했으니 다시 빌드하시고 설치 후 테스트 하시면 될겁니다.
