### ISSUE TITLE
illegal_argument_exception in Elasticsearch 6.0

### ISSUE THREAD

**Issue by kiju98** [HowookJeong/elasticsearch-analysis-arirang#5]
Hi,

Elasticsearch 6.0 produces the following error when I try to analyze "고소/고발" using elasticsearch-analysis-arirang:
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=0,endOffset=2,lastStartOffset=3 for field 'i_title'"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=0,endOffset=2,lastStartOffset=3 for field 'i_title'"
  },
  "status": 400
}
```
I'm not sure if it is an issue from Arirang itself or the plugin. I posted a bug report to http://cafe.naver.com/korlucene/1370 as well.

Thanks and Regards,
Kiju

**Comment by HowookJeong** [comment]
I released from a same version.
This bug is a offset is unsorted.
You can try to reinstall below file.
https://github.com/HowookJeong/elasticsearch-analysis-arirang/releases/download/6.0.0/elasticsearch-analysis-arirang-6.0.0.zip

**Comment by kiju98** [comment]
Thank you for the fix. It works great.
